name: user_repository
description: The Repo that handels users
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-131.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true